#define RESET "[0m"
#define BOLD "[1m"
#define FAINT "[2m"
#define ITALIC "[3m"
#define UNDERLINE "[4m"
#define SLOW_BLINK "[5m"
#define RAPID_BLINK "[6m"
#define INVERT "[7m"
#define CONCEAL "[8m"
#define STRIKETHROUGH "[9m"
#define RED "\033[31m"    /* Red */
#define GREEN "[32m"
#define YELLOW "[33m"
#define BLUE "[34m"
#define MAGENTA "[35m"
#define CYAN "[36m"
#define WHITE "[37m"
#define BRIGHT_BLACK "[90m"
#define BRIGHT_RED "[91m"
#define BRIGHT_GREEN "[92m"
#define BRIGHT_YELLOW "[93m"
#define BRIGHT_BLUE "[94m"
#define BRIGHT_MAGENTA "[95m"
#define BRIGHT_CYAN "[96m"
#define BRIGHT_WHITE "[97m"

#define INFO std::cout << "\t" << __PRETTY_FUNCTION__ << std::endl;
